//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public string Cuenta1 { get; set; }
        public string ClienteCId_fk { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
